import type { Metadata } from "next";
import "./globals.css";
import ClerkClientProvider from "./ClerkClientProvider";
import { FileProvider } from '@/context/FileContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClerkClientProvider><FileProvider>{children}</FileProvider></ClerkClientProvider>
      </body>
    </html>
  );
}
